version: "3.7"

services:
    nodejs:
        image: thanhtv1203/swarm:nodejs
        ports:
            - "8088:8085"
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.5"
                    memory: 100MB
                reservations:
                    cpus: "0.25"
                    memory: 50MB
            restart_policy:
                condition: "on-failure"
    php:
        image: thanhtv1203/swarm:php
        ports:
            - "8086:8082"
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.5"
                    memory: 100MB
                reservations:
                    cpus: "0.25"
                    memory: 50MB
            restart_policy:
                condition: "on-failure"