version: "3.7"

networks:
    net1:
    net2:
        driver: overlay
        name: www-net2
volumes:
    vol1:
        driver: local
        name: v1
        driver_opts:
            type: none
            device: "/home/"
            o: bind
    vol2:
        driver: local
        name: v2
        driver_opts:
            type: cifs
            device: //172.0.0.108/data
            o: "username=smbuser,password=12345678,file_mode=0777,dir_mode=0777"
services:
    samba:
        image: thanhtv1203/samba
        networks:
            - net1
        ports:
            - "139:139"
            - "145:145"
        environment:
            smbuser: smbuser
            password: 12345678        
        volumes:
            - /home/data/:/data/
        deploy:
            replicas: 3
            placement:
                constraints:
                - node.role==manager
    nodejs:
        image: thanhtv1203/swarm:nodejs
        networks:
            - net1
        ports:
            - "8071:8071"
        volumes:
            - vol1:/d1/
            - vol2:/d2/
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.5"
                    memory: 100MB
                reservations:
                    cpus: "0.25"
                    memory: 50MB
            restart_policy:
                condition: "on-failure"
    php:
        image: thanhtv1203/swarm:php
        networks:
            - net2
        ports:
            - "8072:8072"
        volumes:
            - vol1:/d1/
            - vol2:/d2/
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.5"
                    memory: 100MB
                reservations:
                    cpus: "0.25"
                    memory: 50MB
            restart_policy:
                condition: "on-failure"