version: "3.7"

services:
    nodejs:
        image: thanhtv1203/swarm:nodejs
        networks:
            - net1
        ports:
            - "8088:8085"
        volumes:
            - vol1:/d1/
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.5"
                    memory: 100MB
                reservations:
                    cpus: "0.25"
                    memory: 50MB
            restart_policy:
                condition: "on-failure"
    php:
        image: thanhtv1203/swarm:php
        networks:
            - net2
        ports:
            - "8086:8082"
        volumes:
            - vol1:/d1/
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.5"
                    memory: 100MB
                reservations:
                    cpus: "0.25"
                    memory: 50MB
            restart_policy:
                condition: "on-failure"

networks:
    net1:
    net2:
        driver: overlay
        name: www-net2

volumes:
    vol1:
        driver: local
        name: v1
        driver_opts:
            type: none
            device: "/home/"
            o: bind
